main_app/urls.py
from django.urls import path 
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('skills/<int:skill_id>/', views.skill_projects, name='skill_projects'),
      # skills / = resource <int:skill_id>=id views.skill_projects= a method
      # skill_id> can be anything, pizza variable, but try to make it sematic
      # The int: part is called a converter and it's used to match and convert the captured value from a string into, in this case, an integer. If the info in the segment does not look like an integer, then it will not be matched - this is different than what we saw in Express where the type of info in a segment didn't matter.
    # Projects Page
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, 
          document_root=settings.MEDIA_ROOT)

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    # path('accounts/', include('django.contrib.auth.urls')),
]

# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from PIL import Image

class Contact(models.Model): 
    first_name = models.CharField('First', max_length=50)
    last_name = models.CharField('Last', max_length=50)
    company = models.CharField(max_length=100, default="")
    email = models.EmailField('email', max_length=150)
        # https://docs.djangoproject.com/en/2.2/ref/validators/#django.core.validators.EmailValidator
    message = models.TextField(max_length=500, default="")
    submition_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email

TYPES = (
  ('lang','Language'),
  ('frmwk', 'Framework'),
  ('db','Database'),
  ('styl','Styling'),
)

class Skill(models.Model):
    name = models.CharField(max_length=100)
    skill_type = models.CharField(
        'Skill Type',
        # Adds a drop down for skill_type option (language, framework, tool, special)
        max_length = 100,
        choices=TYPES,
            # Sets enumerater option for skill_type choices from tuples 
        # Set Default Type
        default=TYPES[0][0],
            # default to language 
    )
    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return self.name
      # change the default sort
    class Meta:
        ordering = ['name']
            # puts skills in alphabetical order 

class Project(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=250)
    # CharField uses a <input type="text"> as its widget, whereas, a TextField uses a <textarea>
    github = models.URLField(max_length=250)
    image = models.ImageField(default='default.jpg', upload_to='project_pics/')
    description = models.TextField(max_length=500)
    deployment_date = models.DateField()
        # format should be YYYY-MM-DD
    # Create a skill_id FK
    # skill = models.ForeignKey(Skill, default="", on_delete=models.CASCADE) 
        # this is one to many, replaced it with many to many
        # ForeignKey field-type is used to create a one-to-many relationship.
        # Since a project belong to a skill set, project must hold the id of the skill object it belongs to, aka foreign key
        # on_delete=models.CASCADE is required. It ensures that if a Cat record is deleted, all of the child Feedings will be deleted automatically as well - thus avoiding orphan records 
    
    skills = models.ManyToManyField(Skill)

    
    def __str__(self):
        return self.name 

main_app/forms.py
from django import forms
from .models import Contact

# Feeding Form
class ContactForm(forms.ModelForm):
  class Meta:
    model = Contact
    fields = ['first_name', 'last_name', 'company', 'email', 'message']
            # arguments must match fields of Contact model
            # do not need submition date bc it is a non-editable field
            
# form inherits from ModelForm and has a nested class Meta: to declare the Model being used and the fields we want inputs generated for. Confusing? Absolutely, but it's just the way it is, so accept it and sleep well

main_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Project, Skill
from .forms import ContactForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')
 
def skills(request): 
    skills = Skill.objects.all()
    context = {
        'skills': skills
    }
    return render(request, 'skills.html', context)

def skill_projects(request, skill_id):
  skill = Skill.objects.get(id=skill_id)
  context = {
      'skill': skill,
      # these are all the variables we're passing to our template
  }
  return render(request, 'skill_projects.html', context)
    # The skill_projects function is using the get method to obtain the skill object by its id.
    # django will pass any captured URL parameters as a named argument to the view function!

# Projects Page
def index(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'index.html', context)

def contact(request): 
    contact_form = ContactForm(request.POST)
        # create the ModelForm using the data in request.POST
    if contact_form.is_valid():
         new_conact = contact_form.save()
    context = {
        'contact_form': contact_form
    }
    return render(request, 'contact.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About Page</h1>


{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lora Paine</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Parisienne" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">

    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/nav.css">
    <link rel="stylesheet" href="/static/css/projects.css">
{% comment %}     
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script> {% endcomment %}

</head>
    <body>
        <!-- sidebar -->
        <div class="sidenav">
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'about' %}">About</a>
            <a href="{% url 'skills' %}">Skills</a>
            <a href="{% url 'index' %}">Projects</a>
            <a href="{% url 'contact' %}">Contact</a>
        </div>
        <!-- main -->
        <main class="main">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="footer">
            <div class="footer-content">All Rights Reserved, &copy; 2020 Lora Paine &nbsp;</div>
        </footer>
</body>
</html>

main_app/templates/contact.html
{% extends 'base.html' %}
{% block content %}

<h1>Contact Me</h1>

<form action="{% url 'contact' %}" method="post">
    {% csrf_token %}
        {% comment %} as always, we need to include the csrf_token for security purposes {% endcomment %}
        {% comment %} this is causing "This field is required." above every lable {% endcomment %}
    {{ contact_form.as_p }}
        {% comment %} The feeding_form.as_p  will generate the <input> tags wrapped in <p> tags for each field we specified in FeedingForm. {% endcomment %}
    <input type="submit" class="btn" value="Submit">
</form>


{% comment %} need to move the 'onclick' to the submit button and on submit, clear the form and generate a popup saying thank you!  {% endcomment %}
<button onclick = "myfunction()">button</button>
<div class='thank-you'>
    <h1>Thank you for getting in touch!</h1>
    <p>I appreciate you contacting me. I will be sure to get back in touch with you as soon as possible!</p>
    <p>Have a great day!</p>
    <p>Sincerely, </p>
    <p>Lora Paine</p>
</div>
<script>
    function myfunction() {
        console.log("This is a working button");
    }
</script>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Home Page</h1>

{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="title page-title">Projects</h1>
<div class="projects-page">

{% for project in projects %}
    {% include 'partials/card.html' %}
{% endfor %}

</div>
  
  

{% endblock %}

main_app/templates/partials/card.html
{% load static %}

<section class="section reveal load-hidden section-padding">
    <div class="container">
        <div class="columns is-variable bd-klmn-columns is-8">
            <div class="column column1">
                <h1 class="title">{{ project.name }}</h1>
                <br>
                <h2 class="subtitle">{{ project.description}}</h2>
                
                <div class="flex-center">
                <div id="skill-section">
                    <h1>
                        <span class="skill-loop">
                            {% if project.skills.count %}
                                {% for skill in project.skills.all %}
                                <a class="skills" href="{% url 'skill_projects' skill.id %}">
                                    <p>{{ skill.name}}</p>
                                </a>
                                {% endfor %}
                            {% endif %}
                        </span>
                    </h1>
                    <br>
                </div>

                <div id="button-section">
                    <a class="button" href = {{ project.url }} target="_blank">View Project</a>
                    <a class="button" href= {{ project.github }} target="_blank">View The Code</a>
                </div>
            </div>

            </div>

            <div class="column is-6">
                <div class="image-container">
                    <figure class="image is-4by3 image-border">
                        <a href= {{ project.url }} target="_blank">
                            <img class="project-img" src=" {{ project.image.url }}">
                        </a>
                    </figure>
                </div>
            </div>

        </div>
    </div>
</section>

<hr>

<script src="js/main.js"></script>

main_app/templates/partials/skill.html
{% load static %}

<a class="skill-link skills" href="{% url 'skill_projects' skill.id %}">
    <p>{{ skill.name }}</p>
</a>

main_app/templates/skill_projects.html
{% extends 'base.html' %}
{% block content %}

<h1 class="title page-title">Projects Completed Using {{skill.name}} </h1>
<div class="projects-page">

{% for project in skill.project_set.all %}
  {% include 'partials/card.html' %}
{% endfor %}

</div>

{% endblock %}

main_app/templates/skills.html
{% extends 'base.html' %}
{% block content %}

<h1>Skills (Index) Page</h1>
<div class="projects-page">

  <div id="lang" class="skill-loop">
    {% for skill in skills %}
      {% if skill.skill_type == 'lang' %} 
        {% include 'partials/skill.html' %}
      {% endif %}
    {% endfor %}
  </div>

  <div id="frmwk" class="skill-loop">
    {% for skill in skills %}
      {% if skill.skill_type == 'frmwk' %} 
        {% include 'partials/skill.html' %}
      {% endif %}
    {% endfor %}
  </div>

  <div id="db" class="skill-loop">
    {% for skill in skills %}
      {% if skill.skill_type == 'db' %} 
        {% include 'partials/skill.html' %}
      {% endif %}
    {% endfor %}
  </div>

  <div id="styl" class="skill-loop">
    {% for skill in skills %}
      {% if skill.skill_type == 'styl' %} 
        {% include 'partials/skill.html' %}
      {% endif %}
    {% endfor %}
  </div>

</div>



{% endblock %}